### ISSUE TITLE
Extra line is added in `params.yaml` after `opctl init` is run again

### ISSUE THREAD

**Issue by rushtehrani** [onepanelio/core#332] opened 2020-06-05 15:49 UTC
Steps to reproduce:

1. If there is an existing `params.yaml`, remove it and then run `opctl init` for any provider
2. Populate `params.yaml`
3. Run `opctl init` again, the last line in `param.yaml` seems to be partially repeated again.

**Comment by Vafilor** [comment] 2020-06-25 19:02
Unable to reproduce. Closing.

**Closed by Vafilor** 2020-06-25 19:02 UTC
Labels: area/cli, kind/bug
